// components/HeaderNav.vue
<template>
  <div
    class="nav-bar" :class="{ 'absolute w-full h-screen top-0 left-0': menu }">
    <div class="sm:mx-auto flex flex-wrap">

      <!-- Desktop nav -->

      <nav class="container hidden md:inline-flex justify-between px-6 md:px-9 lg:px-16 flex items-center py-2 pt-6">
        <div class="py-4">
          <a href="/"><img src="~assets/img/logo-black.svg" alt="Tableland" class="h-5"></a>
        </div>
        <div class="py-4">
          <ul class="flex justify-end items-center gap-x-3 sm:gap-x-6 md:gap-x-10 lg:gap-x-12 uppercase ml-3">
            <li v-for="(item, index) in items" :key="index">
              <a :href="item.href">
                {{ item.title }}
              </a>
            </li>
            <li><a href="https://docs.tableland.xyz" class="btn bg-black text-white">Get started</a></li>
          </ul>
        </div>
      </nav>

      <!-- Toggle menu mobile -->
      <div class="py-12 px-6 md:hidden logo">
        <a href="/"><img src="~assets/img/logo-black.svg" alt="Tableland" class="h-4"></a>
      </div>
        <button
          class="ml-auto md:hidden p-6" @click="menu = !menu">
        MENU
      </button>
      </div>

      <!-- Mobile nav  -->
      <nav v-show="menu" data-aos="fade-down" class="aos-animate w-full" style="background: #b172a1; transition: all 0.2s ease-in-out">
        <ul class="flex flex-col text-center">
        <li v-for="(item, index) in items" :key="index">
          <a :href="item.href" class="hover: p-6 block">
            {{ item.title }}
          </a>
        </li>
      </ul>
    </nav>
  </div>
</template>

<script>
export default {
  data() {
    return {
      menu: false,
      items: [
        {
          title: 'Blog',
          href: 'https://mirror.xyz/tableland.eth'
        },
        {
          title: 'Rigs',
          href: '/rigs'
        },
        {
          title: 'Discord',
          href: 'https://discord.gg/hpd5WWn4Ys'
        },
        {
          title: 'Docs',
          href: 'https://docs.tableland.xyz'
        }
      ]
    }
  }
}
</script>

// app/components/HeaderNav.tsx
"use client"

import Link from "next/link"
import Image from "next/image"
import { usePathname } from "next/navigation"
import { useState, useEffect } from "react"
import { FaBars, FaTimes } from "react-icons/fa"
import logoBlack from "../../public/img/logo/black.svg"
import logoWhite from "../../public/img/logo/white.svg"

export default function HeaderNav() {
  const pathname = usePathname()
  const [opaque, setOpaque] = useState(false)
  const [menu, setMenu] = useState(false)

  useEffect(() => {
    function checkScroll() {
      setOpaque(window.scrollY > 0)
    }
    checkScroll()
    window.addEventListener("scroll", checkScroll)
  }, [opaque])

  function handleMenu() {
    if (!menu) {
      document.body.style.overflow = "hidden"
    } else {
      document.body.style.overflow = ""
    }
    setMenu(!menu)
  }

  return (
    <header
      className={`fixed top-0 w-full z-50 [transition:background-color_0.2s,border-color_0.3s] ease-out border-b${
        opaque
          ? " bg-darkgreen border-lightgreen text-white"
          : " border-transparent"
      }`}
    >
      <nav className="container mx-auto flex flex-wrap items-center justify-center lg:justify-between px-6 md:px-9 lg:px-16 xl:px-20 py-6 lg:py-4">
        <div className="lg:hidden absolute inset-y-0 left-0 flex items-center px-4">
          <button
            className="inline-flex items-center justify-center"
            onClick={handleMenu}
          >
            <FaBars />
          </button>
        </div>
        <div>
          <Link href="/">
            <Image
              src={opaque ? logoWhite : logoBlack}
              alt="Tableland"
              className={`h-3 md:h-4 w-auto${opaque ? " opacity-[0.87]" : ""}`}
              priority={true}
            />
          </Link>
        </div>
        <div className="hidden lg:block">
          <ul className="flex justify-end text-sm items-center gap-x-2 sm:gap-x-4 md:gap-x-6 lg:gap-x-8">
            <li>
              <Link href="https://github.com/tablelandnetwork" target="_blank">
                GitHub
              </Link>
            </li>
            <li>
              <Link href="https://mirror.xyz/tableland.eth" target="_blank">
                Blog
              </Link>
            </li>
            <li>
              <Link
                href="/pilot-program"
                className={pathname == "/pilot-program" ? "underline" : ""}
              >
                Pilot Program
              </Link>
            </li>
            <li>
              <Link
                href="/rigs"
                className={pathname == "/rigs" ? "underline" : ""}
              >
                Rigs
              </Link>
            </li>
            <li>
              <Link
                href="https://docs.tableland.xyz"
                target="_blank"
                className={`btn-header hover:text-white${
                  opaque ? " bg-white text-black" : " bg-black text-orange"
                }`}
              >
                Docs
              </Link>
            </li>
          </ul>
        </div>
        {menu && (
          <div className="lg:hidden fixed -inset-y-0 z-50 h-screen w-screen overflow-y-scroll bg-darkgreen p-4 md:p-8">
            <div
              className="absolute items-center justify-between right-4 top-4"
              onClick={handleMenu}
            >
              <div className="-mr-2">
                <button
                  type="button"
                  className="inline-flex items-center justify-center p-2 text-white text-2xl"
                >
                  <FaTimes />
                </button>
              </div>
            </div>
            <div className="mt-6 mb-12">
              <div className="pt-2 pb-4 space-y-1 text-white">
                <Link
                  href="https://docs.tableland.xyz"
                  target="_blank"
                  className="block py-2 pl-3 pr-4 hover:underline"
                >
                  Docs
                </Link>
                <Link
                  href="https://github.com/tablelandnetwork"
                  target="_blank"
                  className="block py-2 pl-3 pr-4 hover:underline"
                >
                  GitHub
                </Link>
                <Link
                  href="https://mirror.xyz/tableland.eth"
                  target="_blank"
                  className="block py-2 pl-3 pr-4 hover:underline"
                >
                  Blog
                </Link>
                <Link
                  href="/pilot-program"
                  className="block py-2 pl-3 pr-4 hover:underline"
                >
                  Pilot Program
                </Link>
                <Link
                  href="/rigs"
                  className="block py-2 pl-3 pr-4 hover:underline"
                >
                  Rigs
                </Link>
              </div>
            </div>
          </div>
        )}
      </nav>
    </header>
  )
}
