// app/components/ButtonLink.tsx
import Link from "next/link"
import { type ReactNode } from "react"
import { FaLongArrowAltRight } from "react-icons/fa"

type Props = {
  href: string
  target?: string
  classes?: string
  children: ReactNode
}

export default function ButtonLink({ href, target, classes, children }: Props) {
  return (
    <Link
      href={href}
      target={target ? target : ""}
      className={"btn bg-black text-white " + classes}
    >
      <span className="flex items-center">
        {children}
        <FaLongArrowAltRight className="hidden sm:inline-block ml-3" />
      </span>
    </Link>
  )
}

// components/ButtonLink.vue
<template>
  <a :href="href" class="btn bg-black text-white">
    <span class="flex">
      <slot></slot>
      <img src="~assets/img/arrow_white.png" srcset="~assets/img/arrow_white.png 1x, ~assets/img/arrow_white@2x.png 2x" class="hidden sm:inline-block ml-4" alt="">
    </span>
  </a>
</template>

<script>
export default {
  inheritAttrs: false,
  props: ['href']
};
</script>
