// app/pilot-program/page.tsx
import HeaderNav from "../components/HeaderNav"
import FooterNav from "../components/FooterNav"
import Showcase from "../components/Showcase"
import Link from "next/link"
import ButtonLink from "../components/ButtonLink"
import Image from "next/image"
import { Poppins } from "next/font/google"
import banner from "../../public/img/pilot/community.jpg"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})

export const metadata = {
  title: "Tableland: Pilot Program",
  description:
    "The Pilot Program is here to support you with funding, technical mentors, public showcases, and more. The program is low-lift and high reward for any builder with a vision and dedication.",
}

export default function PilotProgram() {
  return (
    <main className={"min-h-screen " + poppins.className}>
      {/* header */}
      <HeaderNav />
      <div className="pilot-page">
        {/* <!-- hero --> */}
        <section className="page-hero">
          <div className="container mx-auto px-6 md:px-9 lg:px-16 xl:px-20 pt-36 md:pt-48 pb-4 sm:pb-24">
            <div className="flex items-center">
              <div className="xl:w-2/3">
                <h1 className="w-full h-auto font-Orbitron text-4xl md:text-5xl lg:text-6xl xl:text-7xl leading-tighter text-center md:text-left mb-4 md:mb-6 xl:mb-10">
                  Pilot Program
                </h1>
                <p className="text-xl md:text-2xl text-center md:text-left font-light mb-6 md:mb-10">
                  Join the next pilot program season for access to exclusive
                  mentorship, prizes, and a small group building on the cutting
                  edge of the open web.
                </p>
                <p className="text-xl md:text-2xl text-center md:text-left font-light mb-6 md:mb-10">
                  Check out{" "}
                  <Link
                    href="https://youtube.com/playlist?list=PLAc0xDyQDZbo-PnGBbv1aBTVMVwd4qncL"
                    target="blank"
                  >
                    the demos
                  </Link>{" "}
                  from Season 5.
                </p>
                <div className="md:inline-block text-center md:text-left mb-10">
                  <ButtonLink
                    href="https://hhueol4i6vp.typeform.com/pilot-program"
                    target="_blank"
                  >
                    Apply now
                  </ButtonLink>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div className="story">
          {/* <!-- benefits --> */}
          <section id="benefits">
            <div className="section-break"></div>
            <div className="container mx-auto px-6 md:px-9 lg:px-16 xl:px-20 pt-12 pb-24 sm:py-32">
              <h1 className="section-header font-Orbitron w-full h-auto text-5xl lg:text-6xl xl:text-7xl leading-tighter mb-10 lg:mb-18">
                Benefits
              </h1>
              <p className="text-xl lg:text-2xl font-light mb-10 lg:mb-18">
                <Image
                  src={banner}
                  alt="Tableland Community"
                  className="text-flow w-full"
                  priority={true}
                />
                The Pilot Program is here to support you with funding, technical
                mentors, public showcases, and more. The program is low-lift and
                high reward for any builder with a vision and dedication.
              </p>
              <h2 className="w-full h-auto text-xl lg:text-2xl xl:text-3xl mb-6">
                Connect and learn
              </h2>
              <p className="text-xl lg:text-2xl font-light mb-10 lg:mb-18">
                You will receive mentoring from our genesis team and direct
                onboarding onto the Tableland stack. Every team will be granted
                a free Tableland Rig per project.
              </p>
              <h2 className="w-full h-auto text-xl lg:text-2xl xl:text-3xl mb-6">
                Access to Tableland Support
              </h2>
              <p className="text-xl lg:text-2xl font-light mb-10 lg:mb-18">
                Access both funding and dedicated engineering support to help
                your project become real.
              </p>
              <h2 className="w-full h-auto text-xl lg:text-2xl xl:text-3xl mb-6">
                Build Fundable Prototypes
              </h2>
              <p className="text-xl lg:text-2xl font-light mb-10 lg:mb-18">
                Create portfolio-worthy prototypes with the help of mentors and
                peers.
              </p>
              <h2 className="w-full h-auto text-xl lg:text-2xl xl:text-3xl mb-6">
                Marketing and PR
              </h2>
              <p className="text-xl lg:text-2xl font-light mb-10 lg:mb-18">
                Including showcasing work outcomes to the Tableland community,
                inclusion in our private investor newsletter, and our social
                outlets.
              </p>
            </div>
          </section>
        </div>
      </div>
      {/* showcase */}
      <Showcase
        href="https://hhueol4i6vp.typeform.com/pilot-program"
        classes="bg-green border-lightgreen"
      >
        Apply now
      </Showcase>
      {/* footer */}
      <FooterNav />
    </main>
  )
}

// pages/pilot-program.vue
<template>
  <div>
    <!-- Header -->
    <HeaderNav
      :titles="nav.map((i) => i.title)"
      :hrefs="nav.map((i) => i.href)"
      :targets="nav.map((i) => i.target)"
    />
    <div
      class="ship"
      data-aos="fade-down"
      data-aos-anchor=".story"
      data-aos-offset="0"
    ></div>
    <HeaderScrollNav
      anchor=".choose"
      :titles="nav.map((i) => i.title)"
      :hrefs="nav.map((i) => i.href)"
      :targets="nav.map((i) => i.target)"
    />

    <!-- cohort -->
    <section class="cohort">
      <div
        class="container px-6 sm:px-6 md:px-24 lg:px-42 flex items-left pt-64 lg:pt-64"
      >
        <div class="lg:w-2/3 md:w-full" data-aos="fade-up" style="margin: auto">
          <h1
            class="font-Orbitron w-full h-auto text-4xl md:text-5xl lg:text-6xl xl:text-7xl leading-tighter mb-4 lg:mb-10"
          >
            Learn, connect, and build on the frontiers of the Web.
          </h1>
          <p
            class="text-2xl leading-normal md:leading-normal font-light mb-10 lg:mb-18"
          >
            Join our fall pilot program for access to exclusive mentorship,
            prizes, and small group building on the cutting edge of the open
            web.
          </p>
          <a
            href="https://hhueol4i6vp.typeform.com/to/b1VDj6sU"
            class="btn bg-black text-white"
            >Apply Now</a
          >
          <br id="js-scroll" />
        </div>
      </div>
    </section>

    <!-- rig -->
    <section id="about" class="rig">
      <div class="rig-break"></div>
      <div class="container lg:py-16 px-4 lg:px-16">
        <div class="flex">
          <div class="lg:w-2/3 px-2">
            <h1
              data-aos="fade-up"
              class="text-pink font-Orbitron w-full h-auto text-2xl lg:text-4xl leading-tighter mb-0 lg:mb-10"
            >
              Tableland is a composable data network that brings SQL to smart
              contracts on Ethereum and other EVM-compatible chains. Read and
              write structured data to the blockchain to supercharge NFTs,
              games, metaverse experiences, and all of web3.
            </h1>
          </div>
          <div
            data-aos="fade-up"
            data-aos-anchor=".rig"
            class="w-1/3 hidden lg:block"
            style="
              margin-top: -700px;
              overflow: auto;
              position: absolute;
              right: 0;
            "
          >
            <img src="~assets/img/wall.png" />
          </div>
        </div>
        <div class="lg:flex lg:py-12">
          <div class="lg:w-1/2 w-full lg:mt-48 mt-24">
            <img src="~assets/img/wall2.png" />
          </div>
          <div class="lg:w-1/2 px-12 py-12 lg:py-32 lg:mt-32">
            <p
              data-aos="fade-up"
              class="text-pink text-xl lg:text-3xl leading-normal md:leading-normal font-light mb-10 lg:mb-18"
            >
              We’re home to those who are in pursuit of that same vision, and
              we’re ready to support them with tools, resources, and rewards.
            </p>
          </div>
        </div>

        <div class="lg:flex py-12">
          <div class="lg:w-1/2 px-0 py-12">
            <h1
              data-aos="fade-up"
              class="text-pink font-Orbitron w-full h-auto text-3xl lg:text-6xl leading-tighter mb-4 lg:mb-10"
            >
              Tableland is seeking pioneers on a mission to push the boundaries
              of web3.
            </h1>
            <p
              data-aos="fade-up"
              class="text-pink text-xl lg:text-2xl leading-normal md:leading-normal font-light mb-10 lg:mb-18"
            >
              The Pilot Program is here to support you with funding, technical
              mentors, public showcases, and more. Running January 23 to March
              17th, the program is low-lift and high reward for any builder with
              a vision and dedication.
            </p>
            <a
              href="https://youtube.com/playlist?list=PLAc0xDyQDZbo-PnGBbv1aBTVMVwd4qncL"
              class="btn bg-black text-white"
              >Season 5 Demos</a
            >
          </div>
          <div class="lg:w-1/2 lg:mt-48">
            <img src="~assets/img/craft.png" />
          </div>
        </div>
      </div>
    </section>

    <section id="why" class="cohort-info">
      <!-- Airlights -->
      <div class="container px-6 md:px-9 lg:px-16 pt-24">
        <div class="flex py-12 px-12 text-center">
          <div class="w-full px-12 lg:pt-24 py-0">
            <h1
              class="font-Orbitron w-full h-auto text-4xl md:text-5xl lg:text-6xl xl:text-7xl leading-tighter mb-4 lg:mb-10 text-white"
            >
              Why should i apply?
            </h1>
          </div>
        </div>
        <div
          class="grid grid-cols-1 lg:grid-cols-2 justify-center place-content-center py-12 pb-12 lg:px-48 text-center text-white"
        >
          <div class="lg:px-12 py-0">
            <img
              class="icon py-12"
              src="~assets/img/wrench2.png"
              data-aos="fade-up"
            />
            <p class="font-Orbitron text-3xl" data-aos="fade-up">
              Connect and Learn at the Frontier
            </p>
            <br />
            <p
              class="text-xl leading-normal md:leading-normal font-light mb-10 lg:mb-18"
              data-aos="fade-up"
            >
              You will receive mentoring from our genesis team and direct
              onboarding onto the Tableland stack. Connect with other leading
              developers at the frontier.
            </p>
          </div>
          <div class="lg:px-12 py-0">
            <img
              class="icon py-12"
              src="~assets/img/chip2.png"
              data-aos="fade-up"
            />
            <p class="font-Orbitron text-3xl" data-aos="fade-up">
              Access to Tableland Support
            </p>
            <br />
            <p
              class="text-xl leading-normal md:leading-normal font-light mb-10 lg:mb-18"
              data-aos="fade-up"
            >
              Access both funding and dedicated engineering support to help your
              project become real.
            </p>
          </div>
          <div class="lg:px-12 py-0">
            <img
              class="icon py-12"
              src="~assets/img/match2.png"
              data-aos="fade-up"
            />
            <p class="font-Orbitron text-3xl" data-aos="fade-up">Rigs NFT</p>
            <br />
            <p
              class="text-xl leading-normal md:leading-normal font-light mb-10 lg:mb-18"
              data-aos="fade-up"
            >
              Every team will be granted a free Tableland Rig per project to
              continue building and collaborating on the network.
            </p>
          </div>
          <div class="lg:px-12 py-0">
            <img
              class="icon py-12"
              src="~assets/img/wrench2.png"
              data-aos="fade-up"
            />
            <p class="font-Orbitron text-3xl" data-aos="fade-up">
              Build Fundable Prototypes
            </p>
            <br />
            <p
              class="text-xl leading-normal md:leading-normal font-light mb-10 lg:mb-18"
              data-aos="fade-up"
            >
              Create portfolio-worthy prototypes with the help of mentors and
              peers.
            </p>
          </div>
          <div class="lg:px-12 py-0">
            <img
              class="icon py-12"
              src="~assets/img/chip2.png"
              data-aos="fade-up"
            />
            <p class="font-Orbitron text-3xl" data-aos="fade-up">
              Marketing and PR
            </p>
            <br />
            <p
              class="text-xl leading-normal md:leading-normal font-light mb-10 lg:mb-18"
              data-aos="fade-up"
            >
              Including showcasing work outcomes to the Tableland community,
              inclusion in our private investor newsletter, and our social
              outlets.
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- showcase -->
    <section class="md:block showcase py-32 relative">
      <div class="container px-24 md:px-32 lg:px-48">
        <div class="text-center">
          <p
            class="font-Orbitron text-pink text-3xl md:text-4xl lg:text-5xl md:leading-normal lg:leading-normal font-light mb-10"
          >
            Applications now open.
          </p>
          <p
            class="font-Orbitron text-pink text-2xl md:text-2xl lg:text-3xl md:leading-normal lg:leading-normal font-light mb-10"
          >
            If you’re ready to explore the frontiers together
          </p>
          <ButtonLink href="https://hhueol4i6vp.typeform.com/to/b1VDj6sU"
            >Apply Now</ButtonLink
          >
        </div>
      </div>
    </section>
    <FooterNav />
  </div>
</template>

<script>
export default {
  data() {
    return {
      nav: [
        {
          title: "About",
          href: "#about",
        },
        {
          title: "Why?",
          href: "#why",
        },
        {
          title: "Apply Now",
          href: "https://hhueol4i6vp.typeform.com/to/b1VDj6sU",
          target: "_blank",
        },
      ],
    };
  },

  head() {
    return {
      title: "Tableland Pilot Program",
      meta: [
        { hid: "og-url", property: "og:url", content: `${this.$route.path}` },
        { hid: "og-type", property: "og:type", content: "website" },
        {
          hid: "og-title",
          property: "og:title",
          content: "Tableland Pilot Program",
        },
        {
          hid: "og-sitename",
          property: "og:site_name",
          content: "tableland.xyz/pilot-program",
        },
        {
          hid: "og-desc",
          property: "og:description",
          content: "Learn, connect, and build on the frontiers of the Web.",
        },
        {
          hid: "og-image",
          property: "og:image",
          content: "https://i.imgur.com/o1i83B0.jpg",
        },
      ],
    };
  },

  computed: {
    ethereum() {
      return window.ethereum;
    },
  },

  mounted() {
    // eslint-disable-next-line new-cap
    this.lmS = new this.locomotiveScroll({
      el: document.querySelector("#js-scroll"),
      smooth: true,
    });
  },
};
</script>
